name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - flask=3.0.3
  - nltk=3.8.1
  - requests=2.31.0
  - tqdm=4.66.2
  - regex
  - setuptools
  - wheel
  - ca-certificates
  - certifi
  - click
  - colorama
  - idna
  - itsdangerous
  - jinja2
  - joblib
  - markupsafe
  - openssl
  - pysocks
  - urllib3
  - werkzeug
  - zipp
  - pip:
      - filelock==3.13.4
      - fsspec==2024.3.1
      - huggingface-hub==0.22.2
      - keybert==0.8.4
      - lxml==5.2.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - packaging==24.0
      - pillow==10.3.0
      - pygments==2.17.2
      - pypdf2==3.0.1
      - python-docx==1.1.0
      - pyyaml==6.0.1
      - rich==13.7.1
      - safetensors==0.4.3
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - sentence-transformers==2.6.1
      - sympy==1.12
      - threadpoolctl==3.4.0
      - tokenizers==0.15.2
      - torch==2.2.2
      - transformers==4.39.3
      - typing-extensions==4.11.0
